package com.example.akila.myapplication.activites;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.TextView;
import android.os.Bundle;
import com.example.akila.myapplication.R;

// Name: Ananya Srinivasan
// Course: CSC 415
// Semester: Fall 2017
// Instructor: Dr. Pulimood
// SuitUp
// Description: An android app for work clothing donations
// Filename: UsersActivity
// Description: Class for handling the "dashboard"
// Last modified on: 30 November 2017


//User dashboard
public class UsersActivity extends AppCompatActivity implements View.OnClickListener{
    private TextView textView;

    //I overrided the onCreate generated by framework
    @Override
    protected void onCreate(Bundle savedInstanceState){
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_users);

        textView = (TextView)findViewById(R.id.text1);
        String nameFromIntent = getIntent().getStringExtra("EMAIL");
        textView.setText("Welcome " + nameFromIntent);
    }

    @Override
    public void onClick(View v){
        switch(v.getId()){
            case R.id.buttonDonate:
                Intent i = new Intent(UsersActivity.this, Donation.class);
                startActivity(i);
        }
    }

    //Cannot go back to login page
    @Override
    public void onBackPressed() { }
}
